os: linux

dist: xenial

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t lqqojin/dev-simple-docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true lqqojin/dev-simple-docker-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "simple-docker-react-app"
  env: "SimpleDockerReactApp-env"
  bucket_name: "elasticbeanstalk-us-east-2-071673056032"
  bucket_path: "simple-docker-react-app"
  on:
    branch: main
access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_ACCESS_KEY